version: "3.9"

services:
  backend:
    build: .
    deploy:
      replicas: 3
    expose:
      - "8080"

  backend-lb:
    image: nginx:alpine
    ports:
      - "8080:80"
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro